---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
rm(list = ls())
library(sf)
link='midisceplanmap_repro.geojson'
midis=sf::read_sf(link)

```

```{r}
names(midis)
```
```{r}
str(midis)
```

```{r}
library(ggplot2)

#midis
base=ggplot(data=midis) + theme_classic()
base + geom_point(aes(x=yanaProp,
                      y=covidShare,
                      color=porcentajePobrezaExtrema),alpha=0.8) +
    scale_color_distiller(palette ='YlOrRd', direction = 1 ) + 
    labs(x='% beneficiados',
         y='impacto mortalidad del covid post/pre',
         color='% Pobreza\nExtrema',
         title = 'Bono Yanapay',
         subtitle = "Nivel Distrital") +
    geom_hline(yintercept = 0.5, color='grey') +
    annotate(geom = 'text',x = 0.65,y=0.4,label='sin impacto mortalidad Covid', color='grey50') +
    annotate(geom = 'text',x = 0.65,y=-0.95,label='sin muertes desde 2019', color='grey50') +
    annotate(geom = "segment", x = 0.55, y = 0.45, xend = 0.55, yend = 0.3,
         arrow = arrow(type = "closed", length = unit(0.02, "npc"))) 
    
    
```

```{r}
library(ggplot2)

#midis
base=ggplot(data=midis) + theme_classic()
base + geom_point(aes(x=b600prop,
                      y=covidShare,
                      color=porcentajePobrezaExtrema),alpha=0.8) +
    scale_color_distiller(palette ='YlOrRd', direction = 1 ) + 
    labs(x='% beneficiados',
         y='impacto mortalidad del covid post/pre',
         color='% Pobreza\nExtrema',
         title = 'Bono 600',
         subtitle = "Nivel Distrital") +
    geom_hline(yintercept = 0.5, color='grey') +
    annotate(geom = 'text',x = 0.6,y=0.4,label='sin impacto mortalidad Covid', color='grey50') +
    annotate(geom = 'text',x = 0.25,y=-0.95,label='sin muertes desde 2019', color='grey50') +
    annotate(geom = 'text',x = 0.03,y=-0.1,label='sin cobertura del bono', color='grey50',angle=90) +
    annotate(geom = "segment", x = 0.4, y = 0.45, xend = 0.4, yend = 0.3,
         arrow = arrow(type = "closed", length = unit(0.02, "npc"))) 
    
    
```


```{r}

h1=formula(ejecutado_yana~Pres1_PLprop+Congre_PeruLibre_prop+porcentajePobrezaExtrema+covidShare)
reg1=glm(h1,offset = log(programado_yana),family = 'poisson',data=midis)
summary(reg1)

```
```{r}
exp(coef(reg1))
```



```{r}
AER::dispersiontest(reg1,alternative='greater')$ p.value<0.05
```
```{r}
h2=formula(ejecutado_yana~Pres1_PLprop+Congre_PeruLibre_prop+porcentajePobrezaExtrema+covidShare+offset(log(programado_yana)))
```


```{r}
#na.omit(midis)
rbn=MASS::glm.nb(h2,data=midis)#,control=glm.control(maxit=60))

summary(rbn)
```



```{r}
exp(coef(rbn))
```

```{r}
library(ggplot2)
dotwhisker::dwplot(rbn,exp=T)+ geom_vline(
           xintercept = 1,
           colour = "grey60",
           linetype = 2
       )
# + scale_y_discrete(labels=c("trabajo\nindependiente","analfabetismo")) + scale_color_discrete(name="Modelos para:\nCantidad de Asegurados") 

```


